### ISSUE TITLE
[Feature Request] Cron status and logging

### ISSUE THREAD

**Issue by lonix1** [johnbillion/wp-crontrol#45] opened 2019-11-15 12:25 UTC
**First, thanks for a really useful plugin!** 👍 

Please consider adding some of the functionality from [WP-Cron Status Checker](https://wordpress.org/plugins/wp-cron-status-checker/), which would make this plugin feature complete. (Another intersting overlapping plugin is [Advanced Cron Manager](https://wordpress.org/plugins/advanced-cron-manager/)).

Specifically:
- report if cron didn't run, or jobs failed (that plugin uses transients to check every 24 hours)
- show a log of past jobs (time, success/failure)

Future extra bonus unnecessary but cool feature:
- if failure is detected, send an email to the system administrator (optional)

**Comment by johnbillion** [comment] 2019-11-23 12:21
The latest beta version of Crontrol now contains cron event logging. I want to add support for identifying missed cron events, etc. Thanks for the pointers!

**Comment by lonix1** [comment] 2019-11-23 17:24
Looking forward to it. This plugin I think is the best in its class - I've tried them all.

**Comment by danieliser** [comment] 2020-10-20 22:19
@johnbillion Came here to create this exact request. I see you had a beta with ~ a year ago but I don't see that functionality in the current release. Did it never get merged?

Seems silly to have to install a second plugin to monitor logs when this one does everything else so nicely.

**Comment by johnbillion** [comment] 2020-11-24 18:20
Closing as a duplicate of #19.

**Closed by johnbillion** 2020-11-24 18:20 UTC
Labels: enhancement
